spring:
  profiles:
    active:
    - dev
    
---

server:
  port: 9527

spring:
  profiles: dev
  application:
    name: zuul-gateway-9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: zuul-gateway-9527
  company.name: www.ucs.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  routes:
    product.serviceId: mvm-product-8801
    product.path: /product/**
  ignored-services: "*"
  prefix: /mvm3
    
---

server:
  port: 9527

spring:
  profiles: test
  application:
    name: zuul-gateway-9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: zuul-gateway-9527
  company.name: www.ucs.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  routes:
    product.serviceId: mvm-product-8801
    product.path: /product/**
  ignored-services: "*"
  prefix: /mvm3
